### ISSUE TITLE
Rhythms Mechanic

### ISSUE THREAD

**Issue by GelzoneXUnsas** [CPE-476/Dystopian-Virtuosos#4]
- [ ] Synchro
- [ ] Track Editing and Loading
- [ ] Mutliple Tracks
- [ ] Held Notes?

**Comment by bretthickman** [comment]
https://www.reddit.com/r/gamedev/comments/2fxvk4/heres_a_quick_and_dirty_guide_i_just_wrote_how_to/

**Comment by bretthickman** [comment]
https://www.gamedeveloper.com/audio/coding-to-the-beat---under-the-hood-of-a-rhythm-game-in-unity
